logging:
  file:
    name: "logs.log"
spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:memdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
  mvc: 
    dispatch-options-request: true

jwt:
  token:
    secret: RWFRWFRWFWRFDSEQGTHTEDDWFEWGHTBRWEAD
    expired: 120000000
