logging:
  file:
    name: "logs.log"
spring:
  datasource:
    url: jdbc:h2:mem:memdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc: 
    dispatch-options-request: true

jwt:
  token:
    secret: 456SwfZHmzVwtAMpBqjyY5zVtsKA84pBDhPpQWa2cXsLtRk4eFtskuctVjczQCkD
    expired: 31536000000

security:
  access-control-allow-origin: "https://localhost:3000"

server:
  ssl:
    key-store: classpath:e2ee.p12
    key-store-password: 123456
    key-store-type: pkcs12
    key-alias: 1
    key-password: 123456

